In [1]:
import numpy as np

In [2]:
#其他的一些标准运算
B = np.arange(3)
print(B)
print(np.exp(B))#e的x次幂作为新数组元素的值。e为对数函数中常使用的e，近似值为2.718，x为对应位置元素的值
print(np.sqrt(B))#x开平方后的值作为新数组元素的值，x为旧数组对应位置元素的值

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]


In [14]:
#元素向下取整
a = np.floor(np.random.random((3,4))*10)
print("----向下取整----")
print(a)
print("----矩阵结构重置回一维----")
# print(help(np.ravel))
print(a.ravel())
print("----重新设置矩阵----")
print(a.reshape((2,6)))#这个是重新生成新的矩阵，通过元组指定新矩阵结构
a.shape = (2,6)#这里直接修改矩阵的属性，源矩阵结构被改变
print(a)
print("--------")
print(a.T)#装置矩阵，行列结构互换

----向下取整----
[[1. 2. 0. 1.]
 [8. 7. 8. 8.]
 [2. 5. 1. 1.]]
----矩阵结构重置回一维----
[1. 2. 0. 1. 8. 7. 8. 8. 2. 5. 1. 1.]
----重新设置矩阵----
[[1. 2. 0. 1. 8. 7.]
 [8. 8. 2. 5. 1. 1.]]
[[1. 2. 0. 1. 8. 7.]
 [8. 8. 2. 5. 1. 1.]]
--------
[[1. 8.]
 [2. 8.]
 [0. 2.]
 [1. 5.]
 [8. 1.]
 [7. 1.]]


In [17]:
#矩阵拼接
a = np.floor(np.random.random((2,2))*10)
b = np.floor(np.random.random((2,2))*10)
print(a)
print(b)
print("-----vstack行拼接,拼接完毕行数增加，方法名为垂直拼接缩写------")
print(np.vstack((a,b)))

print("-----hstack列拼接,水平拼接，增加列数------")
print(np.hstack((a,b)))

[[5. 0.]
 [4. 1.]]
[[1. 6.]
 [2. 1.]]
-----vstack行拼接,拼接完毕行数增加，方法名为垂直拼接缩写------
[[5. 0.]
 [4. 1.]
 [1. 6.]
 [2. 1.]]
-----hstack列拼接,水平拼接，增加列数------
[[5. 0. 1. 6.]
 [4. 1. 2. 1.]]


In [25]:
#矩阵切分
a = np.floor(10*np.random.random((2,12)))
print(a)
print("----hsplit水平切分矩阵-----")
print(np.hsplit(a,3))#水平切分，每行的元素切分到3个矩阵、
print("----hsplit水平切分矩阵-----")
print(np.hsplit(a,(3,4)))#水平切分，切分第三列到第四列（不包含）
print("----vsplit垂直切分矩阵-----")
print(np.vsplit(a,2))#垂直切分矩阵


[[6. 1. 6. 9. 6. 3. 9. 2. 9. 7. 4. 4.]
 [2. 2. 5. 7. 8. 1. 1. 8. 9. 2. 4. 6.]]
----hsplit水平切分矩阵-----
[array([[6., 1., 6., 9.],
       [2., 2., 5., 7.]]), array([[6., 3., 9., 2.],
       [8., 1., 1., 8.]]), array([[9., 7., 4., 4.],
       [9., 2., 4., 6.]])]
----hsplit水平切分矩阵-----
[array([[6., 1., 6.],
       [2., 2., 5.]]), array([[9.],
       [7.]]), array([[6., 3., 9., 2., 9., 7., 4., 4.],
       [8., 1., 1., 8., 9., 2., 4., 6.]])]
----vsplit垂直切分矩阵-----
[array([[6., 1., 6., 9., 6., 3., 9., 2., 9., 7., 4., 4.]]), array([[2., 2., 5., 7., 8., 1., 1., 8., 9., 2., 4., 6.]])]


In [29]:
#矩阵复制

#同引用的对象操作
a = np.arange(12)
b = a 
print(b is a)
b.shape = (3,4)#修改属性不会生成新对象
print(a.shape)
print(id(a))#id相当于java Hashcode
print(id(b))

True
(3, 4)
1501856392496
1501856392496


In [30]:
#浅复制
c = a.view()
print(c is a)

c.shape = (2,6)
print(a.shape)

c[0,4] = 1234
print(a)
print(id(a))
print(id(c))

#结论，view复制，只是生成一个新的array对象，但对象内部存储数据的数组都只复制了引用
#所以修改复制后的array元素，还是会修改到同一个数组的元素值，view拷贝不推荐使用，表层拷贝。。。

False
(3, 4)
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
1501856392496
1501856391296


In [31]:
#copy实现拷贝
d = a.copy()
print(d is a )
d[0,0] = 9999
print(d)
print(a)

False
[[9999    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
[[   0    1    2    3]
 [1234    5    6    7]
 [   8    9   10   11]]
