In [7]:
import numpy
#向量元素判断
vector = numpy.array([5,10,15,20])
array1 = (vector==10)
print(type(array1))#执行双等号后返回array
print(array1)#array长度与向量相同，元素为每个向量的元素与10比较后的结果

<class 'numpy.ndarray'>
[False  True False False]


In [8]:
#矩阵的判断也一样
matrix = numpy.array([
    [1,2,3,4,5],
    [11,12,13,14,15],
    [21,22,23,24,25],
    [31,32,33,34,35]])
array2 = (matrix%10 == 3)#矩阵元素对10求余后等于3为true
print(type(array2))
print(array2)

<class 'numpy.ndarray'>
[[False False  True False False]
 [False False  True False False]
 [False False  True False False]
 [False False  True False False]]


In [9]:
#返回array中判断为True的值,可以将array当做索引使用，返回一个新的array包含选择的元素
print(vector[array1])
print(matrix[array2])

[10]
[ 3 13 23 33]


In [12]:
vector = numpy.array([1,2,3,4,5])
#与运算符对两个array对应位置的元素进行与运算，返回新的array
equal_to_ten_and_five = (vector==10 )& (vector==5)
print(equal_to_ten_and_five)

#当然也可以进行或运算
equal_to_ten_or_five = (vector==10 )| (vector==5)
print(equal_to_ten_or_five)

[False False False False False]
[False False False False  True]


In [14]:
#numpy类型转换
vector = numpy.array(["1","2","3"])
# print(help(vector))
print(vector.dtype)#获取数组的数据类型
print(vector)
vector = vector.astype(float)#转换元素类型为float
print(vector)

<U1
['1' '2' '3']
[1. 2. 3.]


In [16]:
#python的简洁之处，提供了很多很方便的方法
vector = numpy.array([1,2,3,4,5])
print(vector.min())#array还提供了一些函数可以直接获取所有元素的最大值最小值
print(vector.max())#最大值
print(vector.sum())#统计

1
5
15


In [26]:
matrix = numpy.array(
[
    [5,10,15],
    [20,25,30],
    [35,40,45],
    [50,55,60]
]
)
#print(help(numpy.sum))
print(matrix.sum(axis = 1))#axis = 0为按列操作，axis = 1为按行操作

[ 30  75 120 165]
